<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.jamcracker.testcases.customeManagement.TC004OrderMore" tests="1" time="68.388" ignored="0" failures="1" timestamp="05 Oct 2017 10:18:49 GMT" skipped="0" hostname="tsrajesh" errors="0">
  <testcase name="testOrderMore" time="68.388" classname="com.jamcracker.testcases.customeManagement.TC004OrderMore">
    <failure type="java.lang.AssertionError" message="expected [Thank you for your order. An order confirmation email has been sent to you. Please visit your account subscriptions page to check the status of your order.] but found [Thank you for your request. An email will be sent to you once the order is approved and the offer/stack is ready to use.]">
      <![CDATA[java.lang.AssertionError: expected [Thank you for your order. An order confirmation email has been sent to you. Please visit your account subscriptions page to check the status of your order.] but found [Thank you for your request. An email will be sent to you once the order is approved and the offer/stack is ready to use.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.jamcracker.commonFunctions.customer.OrderMore.orderMore(OrderMore.java:50)
	at com.jamcracker.testcases.customeManagement.TC004OrderMore.testOrderMore(TC004OrderMore.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- testOrderMore -->
</testsuite> <!-- com.jamcracker.testcases.customeManagement.TC004OrderMore -->
